config/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("femlliga.urls")),
    path("civitapp/", include("civitapp.urls")),
]

femlliga/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    # no login required
    path("", views.index, name="index"),
    path(
        "public-announcements/", views.public_announcements, name="public_announcements"
    ),
    path(
        "public-announcements/<uuid:pk>/",
        views.public_announcement,
        name="public_announcement",
    ),
    path(
        "organization/<uuid:organization_id>/announcements/",
        views.announcements,
        name="announcements",
    ),
    path(
        "organization/<uuid:organization_id>/announcements/add/",
        views.add_announcement,
        name="add_announcement",
    ),
    path(
        "organization/<uuid:organization_id>/announcements/<uuid:announcement_id>/",
        views.announcement,
        name="announcement",
    ),
    path(
        "organization/<uuid:organization_id>/announcements/<uuid:announcement_id>/edit/",
        views.edit_announcement,
        name="edit_announcement",
    ),
    path(
        "organization/<uuid:organization_id>/announcements/<uuid:announcement_id>/contacts/<uuid:contact_id>/mark-read/",
        views.mark_announcement_contact_read,
        name="mark_announcement_contact_read",
    ),
    path("maps/", views.maps, name="maps"),
    path("check-matches/", views.check_matches, name="check_matches"),
    path("search-address/", views.search_address, name="search_address"),
    path("page/<slug:name>/", views.page, name="page"),
    # login required
    path("preferences/", views.preferences, name="preferences"),
    path(
        "discard-user-email/<int:pk>/",
        views.discard_user_email,
        name="discard_user_email",
    ),
    path("account/delete/", views.delete_account, name="delete_account"),
    path("app/", views.app, name="app"),
    path("organization/add/", views.add_organization, name="add_organization"),
    path("organization/<uuid:organization_id>/profile/", views.profile, name="profile"),
    path(
        "organization/<uuid:organization_id>/view/",
        views.view_organization,
        name="view_organization",
    ),
    path(
        "organization/<uuid:organization_id>/edit/",
        views.edit_organization,
        name="edit_organization",
    ),
    path(
        "organization/<uuid:organization_id>/delete-logo/",
        views.delete_organization_logo,
        name="delete_organization_logo",
    ),
    path(
        "organization/<uuid:organization_id>/pre-wizard/",
        views.pre_wizard,
        name="pre-wizard",
    ),
    path(
        "organization/<uuid:organization_id>/mid-wizard/",
        views.mid_wizard,
        name="mid-wizard",
    ),
    path(
        "organization/<uuid:organization_id>/reset-wizard/",
        views.reset_wizard,
        name="reset-wizard",
    ),
    path(
        "organization/<uuid:organization_id>/resources-wizard/<str:resource_type>/resource/<str:resource>/",
        views.resources_wizard,
        name="resources-wizard",
    ),
    path(
        "organization/<uuid:organization_id>/resources-wizard/<str:resource_type>/edit/<str:resource>/",
        views.edit_resources_wizard,
        name="force-resources-wizard",
    ),
    path(
        "organization/<uuid:organization_id>/send-message/<uuid:organization_to>/<str:resource_type>/<str:resource>/",
        views.send_message,
        name="send_message",
    ),
    path("organization/<uuid:organization_id>/search/", views.search, name="search"),
    path("organization/<uuid:organization_id>/matches/", views.matches, name="matches"),
    path(
        "organization/<uuid:organization_id>/agreements/",
        views.agreements,
        name="agreements",
    ),
    path(
        "organization/<uuid:organization_id>/agreements/<uuid:agreement_id>/",
        views.agreement,
        name="agreement",
    ),
    # for debugging email style
    #    path(
    #        "organization/<uuid:organization_id>/agreements/<uuid:agreement_id>/email/view/",
    #        views.view_agreement_email,
    #        name="view_agreement_email",
    #    ),
    path(
        "organization/<uuid:organization_id>/agreements/<uuid:agreement_id>/messages/send/",
        views.send_agreement_message,
        name="send_agreement_message",
    ),
    path(
        "organization/<uuid:organization_id>/agreements/<uuid:agreement_id>/messages/<uuid:message_id>/mark-read/",
        views.mark_message_read,
        name="mark_message_read",
    ),
    path(
        "organization/<uuid:organization_id>/agreements/<uuid:agreement_id>/successful/",
        views.agreement_successful,
        name="agreement_successful",
    ),
    path("uploads/<path:path>", views.uploads, name="uploads"),
    path("report/public/", views.report_public, name="report_public"),
    # admin required
    path("report/", views.report, name="report"),
    path("admin/", admin.site.urls),
    # otherwise tested
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

femlliga/models.py
import base64
import math
import unicodedata
import uuid
from datetime import timedelta
from pathlib import Path

import matplotlib.pyplot as plt
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext_lazy as _, ngettext

from . import constants as const


def add_one_month(t):
    t = t.replace(day=1)
    t = t + timedelta(days=32)
    t = t.replace(day=1)
    return t


def add_days(days):
    def f(t):
        return t + timedelta(days=days)

    return f


def date_intervals(start, end):
    start = start.replace(hour=0, minute=0, second=0, microsecond=0)
    if (end - start) < timedelta(days=30):
        f = add_days(1)
    elif (end - start) < timedelta(days=30 * 3):
        f = add_days(7)
    else:
        start = start.replace(day=1)
        f = add_one_month

    intervals = [start]
    mid = start
    while mid < end:
        mid = f(mid)
        intervals.append(mid)

    return intervals


def clean_form_email(s):
    return unicodedata.normalize("NFKC", s.strip()).casefold()


def need_images_directory_path(instance, filename):
    return str(Path("images/needs") / filename)


def offer_images_directory_path(instance, filename):
    return str(Path("images/offers") / filename)


def organization_logos_directory_path(instance, filename):
    return str(Path("images/logos") / filename)


def get_report_statistics():
    o, _created = ReportStatistics.objects.get_or_create()
    return o


@deconstructible
class LimitFileSize:
    def __init__(self, MB):
        self.MB = MB
        self.limit = MB * 1024 * 1024

    def __call__(self, value):
        if value.size > self.limit:
            raise ValidationError(
                _(
                    "L'arxiu és massa gran, hauria d'ocupar menys de %(max)s MB.",
                    max=self.MB,
                )
            )

    def __eq__(self, other):
        return self.MB == other.MB


USER_LANGUAGE_CHOICES = [("", _("Idioma configurat al navegador"))] + [
    x for x in const.LANGUAGE_CHOICES
]


class CustomUser(AbstractUser):
    language = models.CharField(
        max_length=50, choices=USER_LANGUAGE_CHOICES, null=True, blank=True
    )
    distance_limit_km = models.DecimalField(
        max_digits=6, decimal_places=1, default=100
    )  # from 0.0 to 99999.9

    # immediate notifications
    # DEPRECATED
    accept_communications_automatically = models.BooleanField(default=True)
    notify_immediate_communications_received = models.BooleanField(default=True)
    notify_immediate_announcement_communications_received = models.BooleanField(
        default=True
    )
    # DEPRECATED
    notify_immediate_communications_rejected = models.BooleanField(default=True)

    # periodic notifications
    last_notification_date = models.DateTimeField(auto_now_add=True)
    last_long_notification_date = models.DateTimeField(auto_now_add=True)
    notifications_frequency = models.CharField(
        max_length=50, choices=const.NOTIFICATION_CHOICES, default="WEEKLY"
    )
    notify_agreement_communication_pending = models.BooleanField(default=True)
    # DEPRECATED
    notify_agreement_success_pending = models.BooleanField(default=True)
    notify_matches = models.BooleanField(default=True)
    notify_new_resources = models.BooleanField(default=True)

    def get_organization(self):
        organizations = self.organizations.all()
        if len(organizations) > 0:
            return organizations[0]
        return None


class Page(models.Model):
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        primary_key=True,
    )
    name = models.SlugField()
    language = models.CharField(
        max_length=50, choices=const.LANGUAGE_CHOICES, default="ca"
    )
    heading = models.TextField()
    subheading = models.TextField(blank=True)
    content = models.TextField()
    image = models.CharField(max_length=100, blank=True)

    class Meta:
        unique_together = (("name", "language"),)
        verbose_name = _("Pàgina")
        verbose_name_plural = _("Pàgines")

    def __str__(self):
        return f"[{self.language}] {self.name}"


class OrganizationScope(models.Model):
    name = models.CharField(max_length=100, choices=const.ORG_SCOPES, primary_key=True)

    def __str__(self):
        return str(const.ORG_SCOPES_NAMES_MAP[self.name])


class Organization(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    name = models.CharField(max_length=200)
    logo = models.ImageField(
        upload_to=organization_logos_directory_path,
        validators=[LimitFileSize(10)],
        null=True,
        blank=True,
    )
    description = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    scopes = models.ManyToManyField(OrganizationScope)
    org_type = models.CharField(max_length=100, choices=const.ORG_TYPES)
    resources_set = models.BooleanField(default=False)
    lat = models.DecimalField(max_digits=12, decimal_places=9)
    lng = models.DecimalField(max_digits=12, decimal_places=9)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=100)
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        related_name="organizations",
        blank=True,
        null=True,
    )

    welcome_email_sent = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Organització")
        verbose_name_plural = _("Organitzacions")

    def __str__(self):
        return self.name

    @classmethod
    def deleted_organization(cls):
        o = Organization(name=_("«organització eliminada»"), lat=0, lng=0)
        o.id = None  # even if an id is not given, the constructor creates it
        return o

    def json(self, current_organization=None, include_children=False):
        j = {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "org_type": self.org_type,
        }
        # could be a deleted organization
        if self.id:
            j["href"] = reverse(
                "view_organization", kwargs={"organization_id": self.id}
            )
        if current_organization:
            j["distance"] = self.distance_text(current_organization)
        if include_children:
            j["scopes"] = [s.name for s in self.scopes.all()]
            j["social_media"] = [
                {"id": sm.id, "media_type": sm.media_type, "value": sm.value}
                for sm in self.social_media.all()
            ]
            j["needs"] = [
                n.json(current_organization=current_organization, include_org=False)
                for n in self.needs.all()
            ]
            j["offers"] = [
                o.json(current_organization=current_organization, include_org=False)
                for o in self.offers.all()
            ]

        return j

    def type(self):
        for t in const.ORG_TYPES:
            if t[0] == self.org_type:
                return t[1]
        return ""

    def first_resource_not_set(self, resource_type):
        if resource_type == "needs":
            return self.needs_not_set()[0].code
        return self.offers_not_set()[0].code

    def needs_not_set(self):
        return self.aux_not_set(self.needs.all())

    def offers_not_set(self):
        return self.aux_not_set(self.offers.all())

    def aux_not_set(self, data):
        return self.aux_missing_not_set(list(map(lambda x: x.resource, data)))

    def needs_missing(self):
        return self.aux_missing(self.needs.all())

    def offers_missing(self):
        return self.aux_missing(self.offers.all())

    def aux_missing(self, data):
        return self.aux_missing_not_set(
            list(map(lambda x: x.resource, [x for x in data if x.has_resource]))
        )

    def aux_missing_not_set(self, has):
        return [Resource(x) for x in const.RESOURCES if x[0] not in has]

    def has_scope(self, scope):
        return scope in map(lambda x: x.name, self.scopes.all())

    # haversine formula
    def distance(self, other):
        lat1, lon1 = self.lat, self.lng
        lat2, lon2 = other.lat, other.lng

        phi1, phi2 = math.radians(lat1), math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)

        a = (
            math.sin(dphi / 2) ** 2
            + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
        )

        return 2 * 6372.8 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

    def distance_text(self, other):
        d = self.distance(other)
        if d < 1:
            return _("menys d'un km")
        dc = int(math.ceil(d))
        return _("menys de %(d)skm") % {"d": dc}

    def pending_agreements(self):
        sent = self.sent_agreements.filter(
            communication_accepted=True, agreement_successful=None
        ).count()
        received = self.received_agreements.filter(
            communication_accepted=True, agreement_successful=None
        ).count()
        return sent > 0, received > 0

    def pending_announcement_contacts(self):
        announcements = [
            a.pending_contacts()
            for a in self.announcements.all().prefetch_related("contacts")
        ]
        return len(announcements) > 0 and any(announcements)

    def creator__email(self):
        return self.creator.email

    def get_province(self):
        from femlliga.utils import get_province
        from femlliga.gis.es import spain_provinces

        return get_province(self.lat, self.lng, spain_provinces["features"])


class SocialMedia(models.Model):

femlliga/templates/femlliga/add_organization.html
{% extends "femlliga/_base_template.html" %}

{% from 'femlliga/_macros.html' import input_classes, input_value, textarea_value, input_feedback, form_feedback, render_select, render_multi_checkboxes, render_formset_field, render_formset_select, render_formset_delete_vue, leaflet_css, leaflet_js, vue_js, arrow_btn, arrow_btn_content, page_title %}

{% block css %}{{ leaflet_css() }}{% endblock %}

{% block title %}
{% if edit %}
{{ _("Edita l'entitat") }}
{% else %}
{{ _("Crea una entitat") }}
{% endif %}
{% endblock %}

{% block content %}
<div class="container">
{% if edit %}
{{ page_title(_("Edita la informació de l'entitat")) }}
{% else %}
<div class="bg-lightblue text-center br-1rem p-3 mb-2 mt-2" role="alert">
  {{ _("Sembla que encara no heu donat d'alta cap entitat. Per favor, empleneu les dades de sota per crear-la. Podràs modificar i afegir més informació després.") }}
</div>
{% endif %}

{% if form.errors %}
<div class="bg-yellow text-center br-1rem p-3 mb-2 mt-2" role="alert">
  {{ _("Hi ha errors en el formulari. Per favor, corregeix-los i torna a enviar-lo.") }}
</div>
{% endif %}
<form method="post" enctype="multipart/form-data" class="mb-2">
  {{ csrf_input }}
  {{ form_feedback(form) }}

  <div class="py-3">
    <label for="id_name"><strong>{{ _("Nom de l'entitat") }}</strong></label>
    <input type="text" {{ input_classes(form, "name") }} name="name" autocomplete="Nom" id="id_name" {{ input_value(form, "name") }} required>
    {{ input_feedback(form, "name") }}
  </div>

  {# here because if not vuejs does not render it before it calls document.getElementById... #}
  {{ social_media_forms.management_form }}
  <div id="vuejs">
    <div v-if="hasLogo" class="row py-3">
      <div class="col-6">
        {% if org and org.logo %}
          <img class="organization-logo" src="{{ org.logo.url }}" />
        {% endif %}
      </div>
      <div class="col-6">
        <button type="submit" class="btn btn-arrow" @click.prevent="deleteLogo" :disabled="loading">
          <div class="d-flex align-items-stretch">
            <span class="btn-arrow-icon d-flex align-items-center">
              <div v-if="loading" class="spinner-border spinner-border-sm" role="status">
                <span class="visually-hidden">{{ _("Esborrant...") }}</span>
              </div>
              <i v-else class="bi-trash"></i>
            </span>
            <span class="btn-arrow-text">{{ _("Esborra la imatge") }}</span>
            <span class="btn-arrow-arrow d-flex align-items-center"><i class="bi-caret-right-fill"></i></span>
          </div>
        </button>
      </div>
    </div>
    <div v-else class="py-3">
      <label for="id_logo"><strong>{{ _("Logo o imatge de l'entitat") }}</strong> ({{ _("opcional") }})</label>
      <input type="file" {{ input_classes(form, "logo") }} name="logo" autocomplete="Logo" id="id_logo" {{ input_value(form, "logo") }}>
      {{ input_feedback(form, "logo") }}
    </div>

    <div class="py-3">
      <label for="id_description"><strong>{{ _("Descripció de l'activitat de l'entitat") }}</strong> ({{ _("opcional") }})</label>
      <textarea type="text" {{ input_classes(form, "description") }} name="description" autocomplete="Nom" id="id_description">{{ textarea_value(form, "description") }}</textarea>
      {{ input_feedback(form, "description") }}
    </div>

    <div class="py-3">
      <p class="mb-1"><strong>{{ _("Xarxes socials i contacte") }}</strong></p>
      {% for i, mform in enumerate(social_media_forms) %}
        {{ form_feedback(mform) }}
        <div
          class="row mb-2 social-media-wrapper {% if not mform.media_type.value() and not mform.value.value() %}d-none{% endif %}"
          id="social-media-wrapper-{{ i }}"
        >
          <div class="col-md-4 mt-2">
            {{ render_formset_select(mform, mform.media_type, "media_type", "", handler='@change="setMediaType($event)"') }}
          </div>
          <div class="col-md-4 mt-2">
            {{ render_formset_field(mform, mform.value, "value", "text", "", placeholder=media_type_placeholder(mform.media_type.value())) }}
          </div>
          <div class="col-md-4 mt-2">
            {{ render_formset_delete_vue(mform.DELETE, "deleteSocialMedia(" + str(i) + ")") }}
            {{ mform.id }}
            {{ mform.organization }}
          </div>
        </div>
      {% endfor %}
      <div>
        <a
          v-if="socialMediasAddIndex < totalSocialMedias"
          @click.prevent="addSocialMedia"
          href="#"
          role="button"
          class="btn btn-arrow"
        >
          <div class="d-flex align-items-center">
            {{ arrow_btn_content(_("Afegeix xarxa social"), icon="bi-plus-lg") }}
          </div>
        </a>
      </div>
    </div>

    <div class="py-3">
      {{ render_select(form, "org_type", _("Forma jurídica"), strong_label=True) }}
    </div>

    <div class="py-3">
      {{ render_multi_checkboxes(form, "scopes", _("Àmbits")) }}
    </div>

    <div class="py-3">
      <label for="id_address"><strong>{{ _("Ubicació.") }}</strong> {{ _("Indica en el mapa la posició aproximada de l'entitat, o escriu-ne l'adreça aproximada:") }}</label>
      <div class="input-group">
        <input type="text" {{ input_classes(form, "address") }} name="address" autocomplete="Adreça" id="id_address" placeholder="{{ _("Nom del carrer, número, codi postal, població, país") }}" v-model="address">
        <div class="input-group-text">
          <div v-if="loadingAddresses" class="spinner-border spinner-border-sm" role="status">
            <span class="visually-hidden">{{ _("Carregant adreces...") }}</span>
          </div>
          <i v-else class="bi-hourglass"></i>
        </div>
      </div>
    </div>

    <div v-if="noAddresses">
      {{ _("No s'ha trobat cap lloc coincident amb l'adreça indicada. Per favor, indiqueu-ne una altra o concreteu-la més.") }}
    </div>
    <ul v-if="addresses.length > 0">
      <li v-for="address of addresses" :key="address.place_id">
        <a @click="setAddress(address)" class="link-underline-class clickable">{{ _("Selecciona l'adreça:") }}</a> ${ address.display_name }
      </li>
    </ul>

    <input type="hidden" id="lat" name="lat" v-model="lat">
    <input type="hidden" id="lng" name="lng" v-model="lng">
  </div>

  {% if form.errors.lat or form.errors.lng %}
  <div class="invalid-feedback d-block">
    <ul class="errorlist"><li>{{ _("És necessari indicar la posició de l'entitat") }}</li></ul>
  </div>
  {% endif %}
  <div id="citymap" class="map-height"></div>

  {% if edit %}{% set btn_title = _("Desa") %}{% else %}{% set btn_title = _("Crea l'entitat") %}{% endif %}
  <div class="mt-2">
    {{ arrow_btn(btn_title, "bi-floppy") }}
  </div>
</form>
</div>
{% endblock %}

{% block js %}
{{ leaflet_js() }}
{{ vue_js() }}
{{ json_script(consts.SOCIAL_MEDIA_TYPES_PLACEHOLDERS , "media-types-placeholders-data") }}
<script>
var mediaTypesPlaceholdersMap = JSON.parse(document.getElementById('media-types-placeholders-data').textContent);
var map = L.map('citymap').setView([39.98606316571185, -0.03754693138659535], 15);

L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var marker;
{% if form.cleaned_data and form.cleaned_data["lat"] and form.cleaned_data["lng"] %}
marker = L.marker([{{ form.cleaned_data["lat"] }}, {{ form.cleaned_data["lng"] }}]).addTo(map);
{% endif %}

function addSocialMedia(event) {
    var className = "social-media-wrapper";
    var elements = document.getElementsByClassName(className);
    for (let i = 0; i < elements.length; i++) {
        var element = document.getElementById(className + "-" + i);
        if (element.style.display == "none") {
            element.style.display = "flex";
            if (i === elements.length - 1) {
                event.target.style.display = "none";
            }
            return;
        }
    }
}

function createDebounce() {
  let timeout = null;
  return function(f, delayMS) {
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      f();
    }, delayMS || 500);
  };
}

Vue.createApp({
  delimiters: ["${", "}"],
  data() {
    map.on('click', (e) => {
      if (marker) { marker.remove(); }
      marker = L.marker(e.latlng).addTo(map);
      this.updateCoordinates(e);
    });

    return {
      hasLogo: {{ js_bool(org and org.logo) }},
      loading: false,
      socialMediasAddIndex: +document.getElementById("id_social_media-INITIAL_FORMS").value,
      totalSocialMedias: +document.getElementById("id_social_media-TOTAL_FORMS").value,
      mediaTypesPlaceholdersMap: mediaTypesPlaceholdersMap,
      address: "",
      lat: "{% if form.cleaned_data and form.cleaned_data["lat"] %}{{ form.cleaned_data["lat"] }}{% endif %}",
      lng: "{% if form.cleaned_data and form.cleaned_data["lng"] %}{{ form.cleaned_data["lng"] }}{% endif %}",
      debounceAddress: createDebounce(),
      addresses: [],
      noAddresses: false,
    };
  },
  mounted() {
    if (this.lat && this.lng) {
      map.setView([+this.lat, +this.lng], 15);
    }
  },
  methods: {
    deleteLogo() {
      this.loading = true;
      post(
        {% if org %}"{{ url('delete_organization_logo', kwargs={'organization_id': org.id}) }}"{% else %}""{% endif %},
        "{{ csrf_token }}",
        {},
      ).then(response => {
        this.hasLogo = false;
        this.loading = false;
      });
    },
    addSocialMedia() {
      var el = document.getElementById(`social-media-wrapper-${this.socialMediasAddIndex}`);
      el.classList.remove("d-none");
      this.socialMediasAddIndex++;
    },
    deleteSocialMedia(i) {
      document.getElementById(`id_social_media-${i}-DELETE`).value = "on";
      document.getElementById(`social-media-wrapper-${i}`).classList.add("d-none");
    },
    mediaTypePlaceholder(mediaType) {
      var p = this.mediaTypesPlaceholdersMap[mediaType];
      return p || "";
    },
    setMediaType(e) {
      document.getElementById(e.target.id.replace("media_type", "value")).placeholder = this.mediaTypePlaceholder(e.target.value);
    },
    updateCoordinates(e) {
      this.lat = ("" + e.latlng.lat).slice(0, 10);
      this.lng = ("" + e.latlng.lng).slice(0, 10);
    },
    searchAddresses() {
      this.noAddresses = false;
      get("{{ url("search_address") }}?address=" + this.address).then(res => {
        this.addresses = res.addresses;
        this.loadingAddresses = false;
        if (this.addresses.length === 0) {
          this.noAddresses = true;
        }
      });
    },
    setAddress(address) {
      this.lat = address.lat.slice(0, 10);
      this.lng = address.lon.slice(0, 10);
      if (marker) { marker.remove(); }
      marker = L.marker({lat: +this.lat, lng: +this.lng}).addTo(map);
      map.setView([+this.lat, +this.lng], 15);
    },
  },
  watch: {
    address() {
      this.loadingAddresses = true;
      this.debounceAddress(() => {
        if (marker) { marker.remove(); }
        this.lat = "";
        this.lng = "";
        this.searchAddresses();
      });
    },
  },
}).mount("#vuejs");
</script>
{% endblock %}

femlliga/templates/femlliga/aux-wizard.html
{% extends "femlliga/_base_template.html" %}

{% from 'femlliga/_macros.html' import organization_header %}

{% block title %}
{% if page == "pre-wizard" %}
{{ _("Alta") }}
{% elif page == "mid-wizard" %}
{{ _("Meitat d'alta completada") }}
{% else %}
{{ _("Alta completada") }}
{% endif %}
{% endblock %}

{% block content %}
<div class="container less-lg:text-center">
  {{ organization_header(org) }}
  {% if page == "pre-wizard" %}
  <h2>{{ _("Benvinguda!") }}</h2>

  <p>{{ _("Ens agradaria que ens indiques de quins recursos disposeu i quines necessitats teniu. Farem servir aquesta informació per saber amb qui podeu col·laborar.", org_type = org.type().lower()) }}</p>

  <p>{{ _("Et farem una sèrie de preguntes sobre els recursos que teniu o necessiteu. No patisques si tens dubtes sobre el que has de respondre! Podràs modificar totes les respostes més endavant.") }}</p>
  {% elif page == "mid-wizard" %}
  <h2>{{ _("Ja vas per la meitat!") }}</h2>

  <p>{{ _("Has acabat d'introduir les vostres necessitats, només et falta introduir els recursos que podeu oferir a altres.", org_type=org.type().lower()) }}</p>
  {% endif %}

  <form method="POST" action="{{ url(page, args=[org.id]) }}">
    {{ csrf_input }}
    <div class="row mt-3">
      <div class="col-6 d-grid gap-2">
        <button type="submit" class="btn btn-thin" name="start" value="no">{{ _("Ho faré més tard") }}</button>
      </div>
      <div class="col-6 d-grid gap-2">
        <button type="submit" class="btn btn-thin" name="start" value="yes">{{ _("Endavant!") }}</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}